'use client'
import { Activity, ArrowLeftRight, Award, Baby, Badge, BadgeCheck, BarChart, BarChart4, Book, Briefcase, Building2, Car, CarFront, ClipboardEdit, ClipboardList, Contact, Copy, CreditCard, Download, Edit3, Factory, FileBadge, FileEdit, FileSignature, FileText, FileX, Fingerprint, FolderOpen, Globe, Globe2, GraduationCap, Hammer, HardHat, HeartPulse, Home, IdCard, Image as ImageIcon, Landmark, Layers, Link, MessageCircle, Newspaper, AlertTriangle, Printer, Receipt, RefreshCcw, RefreshCw, Scan, School, Settings2, Shield, ShieldCheck, Smartphone, Ticket, UserPlus, UtensilsCrossed, Vote, Wallet, Zap, HelpCircle, Wrench, Phone, BarChart3, Sparkles, ArrowRight, ArrowLeft, MessageSquare, PlayCircle, MapPin, Mail, Calendar, User, Truck, Info, Search, LayoutGrid, RotateCcw, SearchX, Quote, ChevronRight, ChevronLeft, AlertCircle, Clock, CheckCircle2, ChevronDown, ChevronUp, ZoomIn, Play, Pause, Trash2, Edit2, Plus, LogOut, Check, X, Handshake, CircleDollarSign, Headset, Lock, Send, BookOpen, Maximize2, Droplet, Mouse, CheckSquare, PenTool, Tag, Droplets, Target, Eye, Gem, Star, Navigation } from 'lucide-react'

const iconMap = {
  Activity, ArrowLeftRight, Award, Baby, Badge, BadgeCheck, BarChart, BarChart4, Book, Briefcase, Building2, Car, CarFront, ClipboardEdit, ClipboardList, Contact, Copy, CreditCard, Download, Edit3, Factory, FileBadge, FileEdit, FileSignature, FileText, FileX, Fingerprint, FolderOpen, Globe, Globe2, GraduationCap, Hammer, HardHat, HeartPulse, Home, IdCard, Image: ImageIcon, Landmark, Layers, Link, MessageCircle, Newspaper, AlertTriangle, Printer, Receipt, RefreshCcw, RefreshCw, Scan, School, Settings2, Shield, ShieldCheck, Smartphone, Ticket, UserPlus, UtensilsCrossed, Vote, Wallet, Zap, HelpCircle, Wrench, Phone, BarChart3, Sparkles, ArrowRight, ArrowLeft, MessageSquare, PlayCircle, MapPin, Mail, Calendar, User, Truck, Info, Search, LayoutGrid, RotateCcw, SearchX, Quote, ChevronRight, ChevronLeft, AlertCircle, Clock, CheckCircle2, ChevronDown, ChevronUp, ZoomIn, Play, Pause, Trash2, Edit2, Plus, LogOut, Check, X, Handshake, CircleDollarSign, Headset, Lock, Send, BookOpen, Maximize2, Droplet, Mouse, CheckSquare, PenTool, Tag, Droplets, Target, Eye, Gem, Star, Navigation
}

export default function LucideIcon({ name, size = 24, className = '', ...props }) {
  const Icon = iconMap[name] || HelpCircle
  return <Icon size={size} className={className} {...props} />
}

